### ISSUE TITLE
Problem: apache2 address already in use

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica-devtools#42]
Occasionally on running vagrant up, the dashboard doesn't load. Restarting services using ```am services``` results in the following error:

```
* Restarting web server apache2 
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
```

This was on a recent dev branch of Archivematica and qa/0.x of the SS, but it happens regularly with 1.6.x and stable/0.9x as well.

**Comment by sevein** [comment]
I think this is because we used to deploy both Apache and Nginx and they couldn't share TCP ports.

I'm going to close this since AM is only using Nginx these days so it's very unlikely to see this happneing again unless the user is running other server blocks or services using the same TCP ports but if that was the case I'd say it's a conflict that should be solved by the system administrator.
